# Generated by Django 5.0.3 on 2024-03-29 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=400)),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("phone_number", models.BigIntegerField()),
                ("date_created", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("amount", models.FloatField()),
                (
                    "customer",
                    models.ForeignKey(
                        default=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("name", models.CharField(max_length=200)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("price", models.FloatField()),
                ("date_created", models.DateField(auto_now_add=True)),
                ("amount", models.IntegerField()),
                ("url", models.URLField(default="")),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.category"
                    ),
                ),
                ("purchase", models.ManyToManyField(to="api.purchase")),
            ],
        ),
    ]
