# Generated by Django 5.0.3 on 2024-03-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_product_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="pic",
            field=models.ImageField(default="", upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="purchase",
            field=models.ManyToManyField(to="api.purchase"),
        ),
    ]
