# Generated by Django 5.0.3 on 2024-03-27 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_product_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.customer"
            ),
        ),
    ]
