# Generated by Django 5.0.3 on 2024-03-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_customer_pic_alter_product_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="pic",
            field=models.ImageField(default="", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="pic",
            field=models.ImageField(default="", upload_to="images/"),
        ),
    ]
