# Generated by Django 5.0.3 on 2024-03-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_category_pic_product_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="url",
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.CharField(default="", max_length=500),
        ),
    ]
