# Generated by Django 5.0.3 on 2024-03-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_product_url_product_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="category_id",
            new_name="category",
        ),
    ]
