# Generated by Django 5.0.3 on 2024-04-26 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_purchase_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="purhase_product_user",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("product_amount", models.IntegerField()),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
                (
                    "purchase_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.purchase"
                    ),
                ),
            ],
        ),
    ]
