# Generated by Django 5.0.3 on 2024-04-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_purhase_product_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purhase_product_user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
