# Generated by Django 5.0.3 on 2024-04-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_purhase_product_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="purhase_product_user",
            name="purchase_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
